### ISSUE TITLE
Calibrations for Imaging.Confocal.Galvo and Stages.Galvos are not synced.

### ISSUE THREAD

**Issue by ichristen** [mwalsh161/CommandCenter#120]

**Comment by mwalsh161** [comment]
Can you provide more detail? They are synced at a CC level but not at the module level. Currently all calibration is done at CC level. Perhaps this should be reframed to move it to module level?

**Comment by ichristen** [comment]
Maybe the issue was how Noel and Jeff were doing the calibration. Somehow, it was desynced. What is the appropriate way to set the calibration?

**Comment by mwalsh161** [comment]
File -> Camera Calibration
