### ISSUE TITLE
Typo in set_resonator_percent

### ISSUE THREAD

**Issue by cpeng365** [mwalsh161/CommandCenter#99]
https://github.com/mwalsh161/CommandCenter/blob/bcefc1d485c36de6fdad8cabc4ad24a7293d2ffe/Modules/%2BDrivers/%2Bmsquared/solstis.m#L114

100 replaced with `val`

**Comment by mwalsh161** [comment]
Fixed in https://github.com/mwalsh161/CommandCenter/commit/6c90d18585d3aee093a5c558f29efea22cb6cead
